apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hashed-faucet-server.fullname" . }}
  labels:
    {{- include "hashed-faucet-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hashed-faucet-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hashed-faucet-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "src/index.js"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: {{ include "hashed-faucet-server.dbHost" . }}
            - name: PGUSER
              value: "postgres"
            - name: PGDATABASE
              value: "postgres"
            - name: PGPORT
              value: {{ index .Values "hashed-faucet-db" "service" "port" }}
            - name: WSS
              value: {{ .Values.env.wss }}
            - name: NODE_ENV
              value: {{ .Values.env.nodeEnv }}
          envFrom:
            - secretRef:
                name: {{ include "hashed-faucet-server.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
