apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hashed-faucet-server.fullname" . }}
  labels:
    {{- include "hashed-faucet-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGPASSWORD: "{{ index .Values "hashed-faucet-db" "postgresPassword" }}"
  FAUCET_ACCOUNT_SURI: "{{ .Values.env.faucetAccountSURI }}"
