apiVersion: v1
kind: Service
metadata:
  name: {{ include "hashed-faucet-server.fullname" . }}
  labels:
    {{- include "hashed-faucet-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "hashed-faucet-server.selectorLabels" . | nindent 4 }}
