apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdk-services.fullname" . }}
  labels:
    {{- include "bdk-services.labels" . | nindent 4 }}
data:
  config.toml: |
    [default]
    address = "0.0.0.0"
    port = {{ .Values.env.port }}
    network_url = "{{ .Values.env.networkUrl }}"
    network = "{{ .Values.env.network }}"
    pub_key_search_radius = {{ .Values.env.pubKeySearchRadius }}
    log_level = "{{ .Values.env.logLevel }}"