apiVersion: v1
kind: Service
metadata:
  name: {{ include "governance-db.fullname" . }}
  labels:
    {{- include "governance-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "governance-db.selectorLabels" . | nindent 4 }}
