# Default values for hashed-private.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sebastianmontero/hashed-private-action-server-prod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: e519d071e2d04866fc08f3e0bf652b5e17614a64

nameOverride: ""
fullnameOverride: ""

url:
  domain: 
    base: ""
    gql: ""

login:
  challenge:
    timeToLiveMinutes: 5

jwt:
  localKeyPath: ""
  passphrase: ""
  tokenExpirationTimeMins: 60

ingress:
  enabled: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

hasura:
  jwtSecret: '{"jwk_url":"{{ tpl "{{ include \"hashed-private.actionServerUrl\" . }}" . }}/api/jwk/list"}'
  # jwtSecret: '{"jwk_url":"/api/jwk/list"}'
  extraEnv: |-
    - name: EXTERNAL_API_ENDPOINT
      value: "{{ tpl "{{ include \"hashed-private.actionServerUrl\" $ }}" $ }}"
  console:
    enabled: true
  unauthorizedRole: unauthenticated
  imageConfig:
    tag: v2.8.0

  postgresql:
    image:
      tag: "12"
