apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nostr-relays
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nostr-relays-sa
      initContainers:
      - name: demo-aws-cli
        image: amazon/aws-cli
        command: ['aws', 's3', 'cp', 's3://smartvaults-relay-backups/s3-test-file.txt', '-']
      containers:
      - name: my-app
        image: nginx
