apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgraph-backup-script.fullname" . }}
  labels:
    {{- include "dgraph-backup-script.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dgraph-backup-script.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: {{ .Values.env.prometheusPort }}
    targetPort: {{ .Values.env.prometheusPort }}
    protocol: TCP