# Default values for hashed-faucet-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sebastianmontero/smartvaults-rest-server-dev
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: c5551d5380e1dbccf33981dca55f0f521c2b2fb0

nameOverride: ""
fullnameOverride: ""

url:
  domain: 
    base: ""
    subdomain: ""

env:
  pgHost: ""
  pgPassword: ""
  relays: ""
  eventAgeLimitSecs: 30
  nodeEnv: "production"

ingress:
  enabled: true

resources:
  requests:
      cpu: 200m
      memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

