apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-arbitrage-alerter.custom-env-vars-configmap" . }}
  labels:
    {{- include "crypto-arbitrage-alerter.labels" . | nindent 4 }}
data:
  custom-environment-variables.json: |
    {
      "probeAmountUSD": "PROBE_AMOUNT_USD",
      "exchangesById": {
        "kraken": {
          "apiKey": "KRAKEN_API_KEY",
          "secret": "KRAKEN_SECRET"
        },
        "binance": {
          "apiKey": "BINANCE_API_KEY",
          "secret": "BINANCE_SECRET"
        },
        "kucoin": {
          "apiKey": "KUCOIN_API_KEY",
          "secret": "KUCOIN_SECRET",
          "password": "KUCOIN_PASSWORD"
        },
        "bisq": {
          "bisqPassword": "BISQ_API_PASSWORD", 
          "bisqConfig": {
            "rpcHost": "BISQ_RPC_HOST",
            "estimatedTradingFeePercent": "BISQ_TRADING_FEE_PERCENT", 
            "estimatedBtcNetworkFeePerOffer": "BISQ_BTC_NETWORK_FEE",
            "priceApiCallIntervalMs": "BISQ_PRICE_API_INTERVAL_MS"
          }
        }
      },
      "majesticBank": {
        "probeAmountUSD": "MAJESTIC_PROBE_USD",
        "apiBaseUrl": "MAJESTIC_API_URL",
        "cacheTTLSeconds": "MAJESTIC_CACHE_TTL_SECONDS"
      },
      "alerters": {
        "webhook": {
          "url": "WEBHOOK_URL"
        },
        "telegram": {
          "botToken": "TELEGRAM_BOT_TOKEN",
          "chatId": "TELEGRAM_CHAT_ID"
        }
      },
      "logging": {
        "level": "LOG_LEVEL"
      }
    }