apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-arbitrage-alerter.fullname" . }}
  labels:
    {{- include "crypto-arbitrage-alerter.labels" . | nindent 4 }}
data:
  default.hjson: |
     {{- .Values.env | toPrettyJson | nindent 4 }}