apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crypto-arbitrage-alerter.fullname" . }}
  labels: {{- include "crypto-arbitrage-alerter.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegram.botToken}}
