# Default values for document-graph-elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: document-graph-elasticsearch-mainnet
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 352d2ab34dd01b27d83fe01afcb0d8d9ece3175b

nameOverride: ""
fullnameOverride: ""

env:
  contractName: ""
  docTableName: documents
  firehoseEndpoint: ""
  eosEndpoint: ""
  elasticEndpoint: "" #username and password should be set using env vars ES_USER, ES_PASSWORD
  elasticCA: ""
  prometheusPort: 2114
  startBlock: ""
  heartBeatFrequency: 100
  esUser: ""
  esPassword: ""
