# Default values for document-graph-elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sebastianmontero/document-graph-elasticsearch-mainnet
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4d80e26897c524c22beefad5694c4f1fb9d19f69

nameOverride: ""
fullnameOverride: ""

url:
  domain: 
    base: ""
    prometheus: ""

ingress:
  enabled: true

env:
  firehoseEndpoint: ""
  eosEndpoint: ""
  elasticEndpoint: "" #username and password should be set using env vars ES_USER, ES_PASSWORD
  elasticCA: ""
  prometheusPort: 2114
  startBlock: ""
  heartBeatFrequency: 100
  esUser: ""
  esPassword: ""
  dfuseApiKey: ""
  cursorIndexPrefix: ""
  addIntsAsStrings: false
  contracts: []
  singleTextSearchField:
    asset: none
    checksum256: none
    int64: none
    name: none
    time_point: none
    string: none