apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vrf-oracle.fullname" . }}
  labels:
    {{- include "vrf-oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  DFUSE_API_KEY: {{ .Values.env.dfuseApiKey }}
  POSTGRES_PASSWORD: {{ .Values.vrf-db.postgresPassword }}
  VRF_PASSWORD: {{ .Values.vrf-db.vrfPassword }}
  DATABASE_URL: {{ include "vrf-oracle.dbUrl" . }}
  VRF_CONTRACT_KEY: {{ .Values.env.vrfContractKey }}
  VRF_KEY_STORE_PASSWORD: {{ .Values.env.vrfPassword }}
