{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "doccache.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ include "dgraph.alphaDomain" . }}
    {{- if and (.Values.dgraph.ratel.enabled) (ne (include "dgraph.alphaDomain" .) (include "dgraph.ratelDomain" .)) }}
    - {{ include "dgraph.ratelDomain" . }}
    {{- end }}
    {{- if and (ne (include "dgraph.alphaDomain" .) (include "dgraph.prometheusDomain" .)) (or (not .Values.dgraph.ratel.enabled) (ne (include "dgraph.ratelDomain" .) (include "dgraph.prometheusDomain" .)))}}
    - {{ include "dgraph.prometheusDomain" . }}
    {{- end }}
    secretName: {{ include "doccache.fullname" . }}
  rules:
  - host: {{ include "dgraph.alphaDomain" . }}
    http:
      paths:
      - pathType: Prefix
        path: {{ include "dgraph.alphaUrlPathRewrite" . }}
        backend:
          service:
            name: {{ include "dgraph.alphaServiceName" . }}
            port:
              number: 8080
  - host: {{ include "dgraph.prometheusDomain" . }}
    http:
      paths:
      - pathType: Prefix
        path: {{ include "dgraph.prometheusUrlPathRewrite" . }}
        backend:
          service:
            name: {{ include "doccache.fullname" . }}
            port:
              number: {{ .Values.env.prometheusPort }}
  {{- if .Values.dgraph.ratel.enabled }}
  - host: {{ include "dgraph.ratelDomain" . }}
    http:
      paths:
      - pathType: Prefix
        path: {{ include "dgraph.ratelUrlPathRewrite" . }}
        backend:
          service:
            name: {{ include "dgraph.ratelServiceName" . }}
            port:
              number: 8000
  {{- end }}
{{- end }}