apiVersion: v1
kind: Service
metadata:
  name: {{ include "strfry-relay.fullname" . }}
  labels:
    {{- include "strfry-relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    {{- include "strfry-relay.selectorLabels" . | nindent 4 }}
