apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bga-server.fullname" . }}
  labels:
    {{- include "bga-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.env.openaiApiKey }}"
  QDRANT_API_KEY: "{{ .Values.env.qdrantApiKey }}"
  LANGCHAIN_API_KEY: "{{ .Values.env.langchainApiKey }}"  
