apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartvaults-rest-server.fullname" . }}
  labels:
    {{- include "smartvaults-rest-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "smartvaults-rest-server.selectorLabels" . | nindent 4 }}
