apiVersion: v1
kind: Secret
metadata:
  name: {{ include "governance-chatbot-server.fullname" . }}
  labels:
    {{- include "governance-chatbot-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: "{{ include "governance-chatbot-server.dbURL" . }}"
  OPENAI_API_KEY: "{{ .Values.env.openaiApiKey }}"
  PINECONE_API_KEY: "{{ .Values.env.pineconeApiKey }}"
