apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hashed-private.envSecrets" . }}
  labels:
    {{- include "hashed-private.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_KEYS_PASSPHRASE: {{ .Values.jwt.passphrase }}
