apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hashed-private.fullname" . }}
  labels:
    {{- include "hashed-private.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob (include "hashed-private.jwtKeysLocalGlobPath" .) ).AsSecrets | indent 2 }}