# Default values for proxy-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: desneruda/proxy-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

url:
  domain: 
    base: ""
    gql: ""

login:
  challenge:
    timeToLiveMinutes: 5

jwt:
  localKeyPath: ""
  passphrase: ""
  tokenExpirationTimeMins: 60

ingress:
  enabled: true

resources:
    requests:
        cpu: 100m
        memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

hasura:
  jwtSecret: '{"jwk_url":"{{ tpl "{{ include \"proxy-backend.actionServerUrl\" . }}" . }}/api/jwk/list"}'
  # jwtSecret: '{"jwk_url":"/api/jwk/list"}'
  extraEnv: |-
    - name: EXTERNAL_API_ENDPOINT
      value: "{{ tpl "{{ include \"proxy-backend.actionServerUrl\" $ }}" $ }}"
  console:
    enabled: true
  unauthorizedRole: unauthenticated
  imageConfig:
    tag: v2.8.0

  postgresql:
    image:
      tag: "12"
