apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bennyfi-faucet.fullname" . }}
  labels: {{- include "bennyfi-faucet.labels" . | nindent 4 }}
data:
  config.yml: |
    firehose-endpoint: {{ .Values.env.firehoseEndpoint }}
    eos-endpoint: {{ .Values.env.eosEndpoint }}
    start-block: {{ int .Values.env.startBlock }}
    heart-beat-frequency: {{ .Values.env.heartBeatFrequency }}
    dfuse-auth-url: {{ .Values.env.dfuseAuthURL }}
    contract: {{ .Values.env.contract }}
    token-contract: {{ .Values.env.tokenContract }}
    amount-to-send: {{ .Values.env.amountToSend }}
    database-path: /faucet/data/faucet.db
