apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bennyfi-faucet.fullname" . }}
  labels:
    {{- include "bennyfi-faucet.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.class }}