apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bennyfi-faucet.fullname" . }}
  labels: {{- include "bennyfi-faucet.labels" . | nindent 4 }}
type: Opaque
stringData:
  DFUSE_API_KEY: {{ .Values.env.dfuseApiKey }}
  TOKEN_CONTRACT_KEY: {{ .Values.env.tokenContractKey }}
