apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ include "redis-service.name" . }}

