# Default values for bennyfi-jobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sebastianmontero/bennyfi-jobs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.3

nameOverride: ""
fullnameOverride: ""

env:
  bennyfiContract: bennyfi
  eosEndpoints: []
  telosApiEndpoint: https://api.telos.net
  coingecko:
    endpoint: https://api.coingecko.com/api/v3
  contracts:
    - runIntervalMins: 2
      privateKey: ""
      batchActions:
      - action: startpools
        callOnce: false
      - action: timeoutpools
        callOnce: false
      - action: unlockpools
        callOnce: false
      - action: ustkulkpools
        callOnce: false
      - action: ustktmdpools
        callOnce: false
      - action: vestingpools
        callOnce: false
      - action: claimathstks
        callOnce: false
      - action: redraw
        callOnce: true
    - contractName: tlosrex
      runIntervalMins: 1
      privateKey: ""
      batchActions:
        - action: mvfrmsavings
          callOnce: false
        - action: sellrex
          callOnce: false
        - action: withdrawrex
          callOnce: false
  oracle:
    account: benyfioracle
    privateKey: ""
  
  yieldSourceOracles:
    config:
      runIntervalMins: 5
    oracles:
    - name: tlosrex
      yield: 
        provider: telos-api
        key: rex
      token:
        provider: coingecko-api
        key: telos

resources:
    requests:
        cpu: 100m
        memory: 128Mi