# Default values for bennyfi-jobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sebastianmontero/bennyfi-jobs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.3

nameOverride: ""
fullnameOverride: ""

env:
  contractName: ""
  runIntervalMins: 2
  privateKey: ""
  eosEndpoints: []
  batchActions:
  - TimeoutRounds
  - MoveFromSavings
  - SellRex
  - WithdrawRex
  - UnlockRounds
  - UnstakeUnlockedRounds
  - UnstakeTimedoutRounds
  - VestingRounds