apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bennyfi-jobs.fullname" . }}
  labels:
    {{- include "bennyfi-jobs.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bennyfi-jobs.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "bennyfi-jobs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/go/bin/go"]
        args: ["run", ".", "/config/config.yml"]
        volumeMounts:
        - name: bennyfi-jobs-config
          mountPath: /config/config.yml
          subPath: config.yml
        envFrom:
            - secretRef:
                name: {{ include "bennyfi-jobs.fullname" . }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: bennyfi-jobs-config
        configMap:
          name: {{ include "bennyfi-jobs.fullname" . }}