apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bennyfi-jobs.fullname" . }}
  labels:
    {{- include "bennyfi-jobs.labels" . | nindent 4 }}
type: Opaque
stringData:
  PRIVATE_KEY: {{ .Values.env.privateKey }}