apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-gcs-gateway.fullname" . }}
  labels:
    {{- include "minio-gcs-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.env.minioRootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.minioRootPassword }}
