apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-gcs-gateway.fullname" . }}
  labels:
    {{- include "minio-gcs-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: web
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: instance
  selector:
    {{- include "minio-gcs-gateway.selectorLabels" . | nindent 4 }}
