# Default values for bennyfi-faucet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sebastianmontero/bennyfi-faucet-prod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 62218a46009efc00068e4cbeca5f62444bf948d0

nameOverride: ""
fullnameOverride: ""

env:
  contract: ""
  tokenContract: ""
  tokenContractKey: ""
  amountToSend: ""
  firehoseEndpoint: ""
  eosEndpoint: ""
  startBlock: ""
  heartBeatFrequency: 100
  dfuseApiKey: ""
  dfuseAuthURL: ""

storage:
  size: 3Gi
  class: standard