apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-graph-elasticsearch.fullname" . }}
  labels:
    {{- include "document-graph-elasticsearch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "document-graph-elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-graph-elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/go/bin/go"]
        args: ["run", ".", "/config/config.yml"]
        ports:
        - containerPort: {{ .Values.env.prometheusPort }}
          name: prometheus
        volumeMounts:
        - name: dgesearch-config
          mountPath: /config/config.yml
          subPath: config.yml
        envFrom:
        - secretRef:
            name: {{ include "document-graph-elasticsearch.fullname" . }}
      volumes:
      - name: dgesearch-config
        configMap:
          name: {{ include "document-graph-elasticsearch.fullname" . }}