apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-graph-elasticsearch.fullname" . }}
  labels:
    {{- include "document-graph-elasticsearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  ES_USER: {{ .Values.env.esUser }}
  ES_PASSWORD: {{ .Values.env.esPassword }}
