apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-graph-elasticsearch.fullname" . }}
  labels:
    {{- include "document-graph-elasticsearch.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "document-graph-elasticsearch.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: {{ .Values.env.prometheusPort }}
    targetPort: {{ .Values.env.prometheusPort }}
    protocol: TCP