# Default values for crypto-arbitrage-alerter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sebastianmontero/crypto-arbitrage-alerter-prod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: bc2960d867540e0f8e9993a291e169a08fd3a419

nameOverride: ""
fullnameOverride: ""

env:
  probeAmountUSD: 5000
  exchangesById:
    kraken:
      id: kraken
      enabled: true
      feePercent: 0.26
    binanceus:
      id: binanceus
      enabled: false
      feePercent: 0.1
    kucoin:
      id: kucoin
      enabled: true
      feePercent: 0.1
    majesticbank:
      id: majesticbank
      enabled: true
      feePercent: 0
    bisq:
      id: bisq
      enabled: true
      feePercent: 0  # IMPORTANT: Engine will apply 0% fee to prices from BisqAdapter
      bisqConfig:  # Adapter-specific settings for Bisq fee estimation
        estimatedTradingFeePercent: 0.007  # Example: 0.2% (user's best guess for their Bisq trading fee)
        estimatedBtcNetworkFeePerOffer: 0.0001  # Takers perform 3 on chain transactions Example: Avg 5000 sats in BTC
        priceApiCallIntervalMs: 1200

  tradingPairs:
    # - symbol: BTC/USD
    # - symbol: XMR/USD
    - symbol: XMR/BTC

  arbitrage:
    minProfitPercentThreshold: 0.5
    alertCooldownMinutes: 15

  pollingIntervalSeconds: 15

  majesticBank:
    apiBaseUrl: https://majesticbank.sc/api/v1
    cacheTTLSeconds: 300

  alerters:
    console:
      enabled: true
    log:
      enabled: false
    webhook:
      enabled: false
      url: null
    telegram:
      enabled: true
      botToken: null
      chatId: null

  logging:
    level: trace
    logToFile: false
    logFilename: app.log

secrets:
  telegram:
    botToken: null

resources:
    requests:
        cpu: 100m
        memory: 128Mi