apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-backend.envSecrets" . }}
  labels:
    {{- include "proxy-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_KEYS_PASSPHRASE: {{ .Values.jwt.passphrase }}
