apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-backend.fullname" . }}
  labels:
    {{- include "proxy-backend.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob (include "proxy-backend.jwtKeysLocalGlobPath" .) ).AsSecrets | indent 2 }}