apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartvaults-notification-server.envSecrets" . }}
  labels:
    {{- include "smartvaults-notification-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGPASSWORD: "{{ index .Values "smartvaults-server-db" "postgresPassword" }}"
