# Default values for vrf-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: sebastianmontero/vrf-db-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 8334f0d4cb51178e0634b3aeb08ad73ee2e29657

nameOverride: ""
fullnameOverride: ""

password: pg12356789

service:
  port: 5432