apiVersion: v1
kind: Service
metadata:
  name: {{ include "hashed-faucet-db.fullname" . }}
  labels:
    {{- include "hashed-faucet-db.labels" . | nindent 4 }}
spec:
  type: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "hashed-faucet-db.selectorLabels" . | nindent 4 }}
