apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vrf-db.fullname" . }}
  labels:
    {{- include "vrf-db.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.class }}