apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vrf-db.fullname" . }}
  labels:
    {{- include "vrf-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresPassword }}
  VRF_PASSWORD: {{ .Values.vrfPassword }}