apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrf-db.fullname" . }}
  labels:
    {{- include "vrf-db.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vrf-db.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP