apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auxiliar-prospects-api.fullname" . }}
  labels:
    {{- include "auxiliar-prospects-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  LINKEDIN_OAUTH2_ACCESS_TOKEN: "{{ .Values.env.linkedinOauth2AccessToken }}"
  NUBELA_OAUTH2_ACCESS_TOKEN: "{{ .Values.env.nubelaOauth2AccessToken }}"
