apiVersion: v1
kind: Secret
metadata:
  name: {{ include "treasury-oracle.fullname" . }}
  labels:
    {{- include "treasury-oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  DFUSE_EOS_API_KEY: {{ .Values.env.dfuseEOSApiKey }}
  DFUSE_ETH_API_KEY: {{ .Values.env.dfuseETHApiKey }}
  DFUSE_TELOS_API_KEY: {{ .Values.env.dfuseTelosApiKey }}
  EOS_ACCOUNT_KEY: {{ .Values.env.eosAccountKey }}
  
